### ISSUE TITLE
empty htmlClass attributes

### ISSUE THREAD

**Issue by mokadev** [magesuite/theme-creativeshop#1]
Hi,

You have some empty htmlClass attributes in some layout files which triggers an error in developer mode.

**Comment by m-schreiber** [comment]
**Exception Example when in DeveloperMode:**
```
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceContainer', attribute 'htmlClass': [facet 'pattern'] The value '' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_]*(\s[a-zA-Z][a-zA-Z\d\-_]*)*'.
Line: 2071

Element 'referenceContainer', attribute 'htmlClass': '' is not a valid value of the atomic type 'htmlClassType'.
Line: 2071


Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceContainer', attribute 'htmlClass': [facet 'pattern'] The value '' is not accepted by the pattern '[a-zA-Z][a-zA-Z\d\-_]*(\s[a-zA-Z][a-zA-Z\d\-_]*)*'.
Line: 2071

Element 'referenceContainer', attribute 'htmlClass': '' is not a valid value of the atomic type 'htmlClassType'.
Line: 2071

#0 /var/www/vendor/magento/framework/Config/Dom.php(117): Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
```

**Occurrence of empty htmlClass-Attribute:**
https://github.com/magesuite/theme-creativeshop/blob/4bf240cbb63b086a0cb11638e5123f4c4f686533/src/Magento_Catalog/layout/catalog_product_view.xml#L18
https://github.com/magesuite/theme-creativeshop/blob/4bf240cbb63b086a0cb11638e5123f4c4f686533/src/Magento_Cms/layout/cms_page_view.xml#L26
https://github.com/magesuite/theme-creativeshop/blob/4bf240cbb63b086a0cb11638e5123f4c4f686533/src/MageSuite_ContentConstructor/layout/contentconstructor_components_index.xml#L17

**Comment by krzksz** [comment]
Thank you for your report, fixed in https://github.com/magesuite/theme-creativeshop/commit/d0110463bf223764af9673314c3b892f9babd698
