### ISSUE TITLE
Icon flag in the store selector

### ISSUE THREAD

**Issue by nandopsilva** [magesuite/theme-creativeshop#10]
Hello!

This is just a question.

How to change the icon flag in the store selector? I didn't find any place to change in the admin.

Thank you!

Best Regards,
Fernando Silva

**Comment by ptylek** [comment]
Hi @nandopsilva ,
If you want to change flag then you have to add `flag_<store-code>.svg` in your theme so for example for Netherlands in <theme_dir>/web/images/icons/`flag_nl.svg`
Best regards,
Pawel

**Comment by nandopsilva** [comment]
Hello @ptylek !

Thank you very much for your answer.

Best Regards,
Fernando Silva
