### ISSUE TITLE
ThemeHelpers: Enable WebP support

### ISSUE THREAD

**Issue by tim-breitenstein-it** [magesuite/theme-creativeshop#101]
> Enabling this feature will append .webp extension to all image urls to achieve better image compression while maintaining good quality. This setting requires special web server configuration. Enabling it without such configuration might break images rendering.

Is there any documentation on configuring the web server to support webp images? 

See https://github.com/magesuite/theme-helpers/issues/2

**Comment by drabikowy** [comment]
Hello! 
this webp support was totally unreliable. 
Our MageOps team developed image optimziation in the infratructure instead. https://github.com/mageops/ansible-infrastructure/

We will remove webp related configuration soon. 


Best regards
