### ISSUE TITLE
GDPR and Google Fonts

### ISSUE THREAD

**Issue by sylphlv** [magesuite/theme-creativeshop#106]
Hello!

Please move the Google Fonts to the repository, instead of loading them from Google's servers.
They are not GDPR compliant and will get shop owners in trouble. [1]

There is more, but just one example of the issue:
https://github.com/magesuite/theme-creativeshop/blob/8192f40efc223f32be3b90ce5ced579a5f7fe5eb/src/Magento_Theme/layout/default.xml#L12

References:
1. LG München, Urteil vom 19.01.2022, Az. 3 O 17493/20. https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/

**Comment by diwipl** [comment]
Hi
Thank you for the report.

The issue is already solved in the 18.x branch of theme-creativeshop https://github.com/magesuite/theme-creativeshop/blob/18.x/src/Magento_Theme/layout/default.xml

It will be released officially along with compatibility with Magento 2.4.5.

**Comment by sylphlv** [comment]
Great, thank you!
