### ISSUE TITLE
Metadata (rich snippets) missing in price template

### ISSUE THREAD

**Issue by fritzmg** [magesuite/theme-creativeshop#107]
The current [price template](https://github.com/magesuite/theme-creativeshop/blob/next/src/Magento_Catalog/templates/product/price/amount/default.phtml) is missing the `itemprop="offers" itemscope itemtype="http://schema.org/Offer"` attributes in the price container, as well as the

```php
<meta itemprop="price" content="<?= $block->escapeHtmlAttr($block->getDisplayValue()) ?>" />
<meta itemprop="priceCurrency" content="<?= $block->escapeHtmlAttr($block->getDisplayCurrencyCode()) ?>" />
```

meta data output. Is there a specific reason for this? If not I could provide a PR that re-introduces this metadata again.

**Comment by drabikowy** [comment]
Hello @fritzmg,
we introduced a separate module for google structured data generation, with many configuration possibilities as well, you can check it out:
https://github.com/magesuite/google-structured-data
