### ISSUE TITLE
Is this repo inactive and no longer maintainance

### ISSUE THREAD

**Issue by mrtuvn** [magesuite/theme-creativeshop#116]
This is good theme magento as i watch in daily works basis. But seem quite long i don't see new commit. Is this repo no longer maintanance right. Can you share any updates or road map

**Comment by nicoren-tangkoko** [comment]
@mrtuvn : Hello, this repo seems not to be inactive. check 20.x branch (https://github.com/magesuite/theme-creativeshop/tree/20.x).

**Comment by diwipl** [comment]
@nicoren-tangkoko I've changed now `20.x` to be the default branch to avoid (correct) confusion that the repository is not active
