### ISSUE TITLE
referenceBlock with group-attribute not allowed

### ISSUE THREAD

**Issue by m-schreiber** [magesuite/theme-creativeshop#2]
On loading a Product-View the following exception occurs:
```
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2883

Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2890

Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2915

Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2924


Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2883

Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2890

Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2915

Element 'referenceBlock', attribute 'group': The attribute 'group' is not allowed.
Line: 2924

#0 /var/www/vendor/magento/framework/Config/Dom.php(117): Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
```

The reason is the use of the `group`-Attribute on `referenceBlock`-Tags inside Layout-XML:
https://github.com/magesuite/theme-creativeshop/blob/c3a8c79ee4a9675eae138da5411f478bfea935b4/src/Magento_Catalog/layout/catalog_product_view.xml#L247
https://github.com/magesuite/theme-creativeshop/blob/c3a8c79ee4a9675eae138da5411f478bfea935b4/src/Magento_Catalog/layout/catalog_product_view.xml#L255
https://github.com/magesuite/theme-creativeshop/blob/c3a8c79ee4a9675eae138da5411f478bfea935b4/src/Magento_Catalog/layout/catalog_product_view.xml#L283
https://github.com/magesuite/theme-creativeshop/blob/c3a8c79ee4a9675eae138da5411f478bfea935b4/src/Magento_Catalog/layout/catalog_product_view.xml#L295

**Comment by m-schreiber** [comment]
found one more:
```
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'after': The attribute 'after' is not allowed.
Line: 2463


Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'after': The attribute 'after' is not allowed.
Line: 2463
```
https://github.com/magesuite/theme-creativeshop/blob/c3a8c79ee4a9675eae138da5411f478bfea935b4/src/Magento_Customer/layout/customer_account.xml#L89

**Comment by m-schreiber** [comment]
by the way - the first two can be fixed by replacing them with this:
`src/Magento_Catalog/layout/catalog_product_view.xml`
```
<referenceBlock name="product.info.details.main">
            <block class="Magento\Catalog\Block\Product\View\Description" name="product.info.description" as="description" template="Magento_Catalog::product/view/attribute.phtml" group="column_left">
                <arguments>
                    <argument name="title" translate="true" xsi:type="string">Description</argument>
                    <argument name="contain_content" xsi:type="boolean">false</argument>
                    <argument name="sort_order" xsi:type="string">10</argument>
                    <argument name="at_call" xsi:type="string">getDescription</argument>
                    <argument name="at_code" xsi:type="string">description</argument>
                    <argument name="css_class" xsi:type="string">description</argument>
                    <argument name="at_label" xsi:type="string">none</argument>
                </arguments>
            </block>
            <block class="Magento\Catalog\Block\Product\View\Attributes" name="product.attributes" as="additional" template="Magento_Catalog::product/view/attributes.phtml" group="column_right">
                <arguments>
                    <argument name="contain_content" xsi:type="boolean">false</argument>
                    <argument name="sort_order" xsi:type="string">20</argument>
                    <argument translate="true" name="title" xsi:type="string">More Information</argument>
                </arguments>
            </block>
        </referenceBlock>
```

**Comment by seyuf** [comment]
Any update on this issue? 
Can’t we just remove the group attributes for the moment? 
It seems to be working fine without...

**Comment by krzksz** [comment]
Thanks for your report, we are working on this issue and will provide a fix for it.

**Comment by berbua** [comment]
Exceptions reported on Jul 17th fixed with https://github.com/magesuite/theme-creativeshop/commit/bbec9401d0f2e16a5cb1c9a381abbeccc397d8ef

**Comment by berbua** [comment]
Hello @m-schreiber, please be informed that the issue related to `group` attribute has been reported to Magento:
[https://github.com/magento/magento2/issues/24656](https://github.com/magento/magento2/issues/24656)

**Comment by viliusramulionis** [comment]
Hello,

Im getting the same error.
Running magento 2.3.3 and Magesuite 3.0
Product page doesn't work unless i modify theme-creativeshop's layout file to remove groups from referenceBlock tags.

Some help would be appreciated.

**Comment by krzksz** [comment]
Hello @viliusramulionis, as we outlined in the https://github.com/magento/magento2/issues/24656 it is an issue with the XML validator itself. Until it is fixed, the temporary solution is to switch from `developer` to `default` mode when developing the shop as in both `default` and `production` modes everything is fine.

**Comment by Flowlance** [comment]
Same issue here in developer mode.

**Comment by tim-breitenstein-it** [comment]
Still exists on Magento 2.4.2

**Comment by tim-breitenstein-it** [comment]
Still exists on Magento 2.4.2-p1

**Comment by fritzmg** [comment]
@tim-breitenstein-it according to the aforementioned ticket, it will be fixed in Magento `2.4.3`.

**Comment by fritzmg** [comment]
Magento `2.4.3` was released recently, however this issue still exists there unfortunately.

**Comment by fritzmg** [comment]
Until this is actually fixed in Magento itself, you can do the following:

1. Run `composer require cweagans/composer-patches`.
2. Create a `patches/allow-group-attribute-for-referenceblock.patch` file with this [1] content.
3. Add this [2] to your `composer.json`.
4. Run `composer install` to apply the actual patch.

[1]

```diff
--- a/vendor/magento/framework/View/Layout/etc/elements.xsd
+++ b/vendor/magento/framework/View/Layout/etc/elements.xsd
@@ -328,6 +328,7 @@
         <xs:attribute type="elementNameType" name="name" use="required"/>
         <xs:attribute type="xs:string" name="template" use="optional"/>
         <xs:attribute type="xs:string" name="class" use="optional"/>
+        <xs:attribute type="xs:string" name="group" use="optional"/>
         <xs:attribute type="xs:boolean" name="display" default="true" use="optional"/>
         <xs:attribute type="xs:boolean" name="remove" use="optional"/>
     </xs:complexType>
```

[2]

```json
    "extra": {
        "patches": {
            "magento/framework": {
                "Allow group attribute for referenceBlock": "patches/allow-group-attribute-for-referenceblock.patch"
            }
        }
    }
```
