### ISSUE TITLE
Typo in calling plural translation in rating-stars.phtml:39

### ISSUE THREAD

**Issue by pastanislas** [magesuite/theme-creativeshop#3]
On a fresh magento 2.3.2 install  + sample datas + elasticsuite 2.8.X
I had to change line 39 from 

 $reviewsCountMessage = $reviewsCount . '<span class="cs-star-rating__text-annotation"> ' . ($reviewsCount == 1 ? __('review') : _('reviews')) . '</span>';

to (double underscore)

 $reviewsCountMessage = $reviewsCount . '<span class="cs-star-rating__text-annotation"> ' . ($reviewsCount == 1 ? __('review') : __('reviews')) . '</span>';

Fatal error: Uncaught Error: Call to undefined function _() in /var/www/html/app/design/frontend/creativestyle/theme-creativeshop/Magento_Review/templates/rating-stars.phtml:39 Stack trace: #0 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
/var/www/html/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Framework\View\Element\Template\Interceptor), '/var/www/html/a...', Array)
/var/www/html/generated/code/Magento/Framework/View/Element/Template/Interceptor.php(102): Magento\Framework\View\Element\Template->fetchView('/var/www/html/a...') 

/var/www/html/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template\Interceptor->fetchView('/var/www/html/a...') #4 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1094): Magento\Framework\View\Element\Template->_toHtml() #5 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php(1098): Magento\Fra in /var/www/html/app/design/frontend/creativestyle/theme-creativeshop/Magento_Review/templates/rating-stars.phtml on line 39

**Comment by krzksz** [comment]
Thanks for your report! We are working on this issue.

**Comment by berbua** [comment]
Thank you for reporting, fixed in https://github.com/magesuite/theme-creativeshop/commit/e93c04efd0a81bc00ccd4a4fa161f2dc0a9ed950
