### ISSUE TITLE
./preview.png magesuite-theme-generator

### ISSUE THREAD

**Issue by thomas7467** [magesuite/theme-creativeshop#30]
Hi,
I have this error when running .yarn/bin/magesuite-theme-generator

Cloning CreativeShop repository to use as a base...
Adjusting registration.php file...
Adjusting composer.json file...
Adjusting theme.xml file...
Adding default preview file...
ENOENT: no such file or directory, stat './preview.png'

How can I solve this?
Thank you

**Comment by ggm-dev** [comment]
@thomas7467  - Copy the preview.png file from theme-creativesuite/src to <your custom theme>/src and error should go away.

**Comment by thomas7467** [comment]
Hi,
I can copy the file in the new template directory after the error, but is the magesuite-theme-generator process complete?
theme-creativeshop folders and files and the new one generated are not similar in content; the new one contents less files and folders...
Relaunching the magesuite-theme-generator indicates that the new theme folder exists...

**Comment by thomas7467** [comment]
@ggm-dev : thanks ! works fine now.

**Comment by roman204** [comment]
> @thomas7467 - Copy the preview.png file from theme-creativesuite/src to /src and error should go away.

for anyone running into this issue and find that comment, it means the preview.png file has to be in that folder where the command (magesuite-theme-generator) is executed
for example if your pwd is the directory /var/www/htdocs then the file has to be /var/www/htdocs/preview.png
