### ISSUE TITLE
Shopping cart frame

### ISSUE THREAD

**Issue by thomas7467** [magesuite/theme-creativeshop#31]
Hi,
On a new installation of the last version , the cart frame shows 2 empty rectangles 

![cart](https://user-images.githubusercontent.com/5119428/98379857-14956000-2048-11eb-9201-5062390593b5.jpg)

instead of "empty cart" like on creativshop test server

![cart2](https://user-images.githubusercontent.com/5119428/98380078-650cbd80-2048-11eb-9702-73331b72b5b6.jpg)

Any ideas?

Thank you
Thomas

**Comment by thomas7467** [comment]
I'm closing this isssue, probably due to magento 2.4.1 version; it works with 2.4.0 version.

**Comment by ggm-dev** [comment]
This is an issue for us too on 2.4.1 but not on 2.4.0. @thomas7467, would you mind re-opening the ticket?  Perhaps the core team can provide a fix for 2.4.1.

**Comment by krisdante** [comment]
We started work on 2.4.1 but we cannot commit to any date. The end of the year is crazy in the business :)
