### ISSUE TITLE
Link_Previous hidden when using combined burger and search in mobile nav

### ISSUE THREAD

**Issue by ggm-dev** [magesuite/theme-creativeshop#34]
I set "mobile_search_in_offcanvas" to true in view.xml.  When you click into a category the link_previous is hidden under search, making it impossible to navigate back up category tree.  

<img width="1068" alt="Screen Shot 2020-11-13 at 9 04 27 AM" src="https://user-images.githubusercontent.com/66025527/99087144-0b4c4c00-2590-11eb-90c1-bf6ca6cfa7cb.png">

**Comment by ggm-dev** [comment]
Any updates on this issue or can anyone else confirm that they're having same problem?

**Comment by berbua** [comment]
Hi @ggm-dev thanks for the heads up. Please be informed that the issue has been fixed - the position of the list has been adjusted (has just been merged so will be visible on Github within 24hours).

**Comment by ggm-dev** [comment]
Great!
