### ISSUE TITLE
Element 'referenceBlock', attribute 'after': The attribute 'after' is not allowed.

### ISSUE THREAD

**Issue by Lukas-G21** [magesuite/theme-creativeshop#4]
When accessing customer account page this error occurs:
1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException): Element 'referenceBlock', attribute 'after': The attribute 'after' is not allowed.
Line: 2842.

File that causes this: /vendor/creativestyle/theme-creativeshop/src/Magento_Customer/layout/customer_account.xml has referenceBlock after tags.

**Comment by berbua** [comment]
Thank you for reporting, fixed in e93c04e
