### ISSUE TITLE
Footer Newsletter from  & social icons elements not shown

### ISSUE THREAD

**Issue by thomas7467** [magesuite/theme-creativeshop#42]
Hi,

Magento 2.4.0
PHP 7.4.3

Newsletter form and social icons are hidden after creativshop theme deployment is that normal?
On the demo site they appear like this :

![footer](https://user-images.githubusercontent.com/5119428/101635142-dc5bb580-3a29-11eb-9995-454099fd35d5.png)

I can see the three footer links block in Magento_theme/layout/default.xml  for the sample links; they appear.

![footer2](https://user-images.githubusercontent.com/5119428/101635819-c1d60c00-3a2a-11eb-9cf6-4831b2de45cc.png)

But social icons are hidden even if the container seems to be defined 

```
 <container name="footer.element.extras" htmlTag="div" htmlClass="cs-footer__item cs-footer__item--extras">
                <block name="footer.socials" template="Magento_Theme::footer/section.phtml">
```

And no section for the newsletter subscription - could someone give me a clue?

Thks
Thomas

**Comment by mborkowski** [comment]
Hi @thomas7467 
We haven't notice this issue, everything seems to be fine with the latest build. Did you modify XML/phtml files? If so, maybe error log (`var/log/system.log`) will tell you why they're not rendered.

**Comment by thomas7467** [comment]
Hi @mborkowski 
I will again from scratch and let you know; wich version of PHP will you support vs Magento 2.4.0 one?
When will you be compatible with magento 2.4.1?
BR Thomas

**Comment by mborkowski** [comment]
At this mooment we can confirm support for Magento 2.4.0 and PHP 7.3. We are working on Magento 2.4.1 and PHP 7.4 but can't guarantee no bugs related to these versions.

**Comment by thomas7467** [comment]
Hi,
Reinstalled from scratch on DEBIAN 10, PHP 7.3.19, NGINX 1.14.2 : Newsletter and Social icons are shown - I close the ticket.
Thks Thomas
