### ISSUE TITLE
Add to cart : Something went wrong

### ISSUE THREAD

**Issue by thomas7467** [magesuite/theme-creativeshop#52]
Hi Dev Team,

I've noticed the following behaviour when adding a product to cart ( click on Add to cart from product page) : button hover switches to red with message "something went wrong" but the product was added correctly to the cart.
Message appears on your demo store too from laptop or mobile and on my test server with 1000 products.
if the hosting server is slow the message will be visible longer.

![add_to_cart](https://user-images.githubusercontent.com/5119428/103629587-cc5bc680-4f40-11eb-8d5a-e5c9ca83ba14.png)
 
Is there a way to solve this?
Thks Thomas

**Comment by mborkowski** [comment]
Hi @thomas7467 
I'd need some reproduction path including url to the affected product. I've tested 3 products and I didn't notice anything like that.

**Comment by mborkowski** [comment]
Or maybe I got you wrong. Does this appear on the storefront or you're just getting it selected within the dev tools right after you click "inspect"?

**Comment by thomas7467** [comment]
Hi @mborkowski ,
It appeared on the store front.
Reinstalled all the components from scratch with PHP 7.3 that you support, instead 7.4, and now its working fine. I close the issue.

**Comment by Wacek-Tarkowski** [comment]
Hi!
We have the same problem like by thomas7467 on our preproduction store but the product was added correctly to the cart.

PHP ver 7.4.21
Magento ver. 2.4.3-p1

Thanks for any help or advice!

<img width="1680" alt="Screenshot 2022-07-19 at 09 54 31" src="https://user-images.githubusercontent.com/103731558/179697851-fee1ab5c-64b0-4074-add5-617b45bd6092.png">
