### ISSUE TITLE
v11.0.0 Release and magesuite requirements

### ISSUE THREAD

**Issue by ggm-dev** [magesuite/theme-creativeshop#54]
Hi All - Do you intend to update Magesuite requirements for latest release of createshop theme or is there more work to be done before it is fully compatible?  

Thanks!
David

**Comment by diwipl** [comment]
Hi,

Yes, we do. We are preparing release notes with info which changes are breaking compatibility ones so everybody knows what needs a rewrite in child themes.

**Comment by diwipl** [comment]
Hi

MageSuite v7.0.0 just got released along with a bump of theme-creativeshop to v11

**Comment by ggm-dev** [comment]
That's great news!  Thanks for update.   I've been searching for any info regarding correct way to update child theme - I see that node modules were update in theme-creativesuite.  

I've updated magesuite to 7.0 and running on 2.4.1 and don't have any issues with my child theme yet, but am curious about what you recommend.
