### ISSUE TITLE
Custom layout updates must be selected from a file

### ISSUE THREAD

**Issue by nandopsilva** [magesuite/theme-creativeshop#6]
When trying to save a CMS page, displays a message: 

**Custom layout updates must be selected from a file.**

Magento 2.3.4
Php 7.2
"creativestyle/magesuite": "^3.0",
"smile/elasticsuite": "^2.8"

**Comment by krzksz** [comment]
Hey! We are working on an update to the whole MageSuite that will make it compatible with 2.3.4, stay tuned!

**Comment by nandopsilva** [comment]
Thanks for the answer.

I look forward to test and to contributing.

When the repository is updated, will there be any notifications?

**Comment by Niels-P** [comment]
Looking for a fix as well, would be great if this could be patched A.S.A.P.

**Comment by nandopsilva** [comment]
Testing in Magento 2.3.4. So far everything is ok!

Magento 2.3.4
Php 7.2
"creativestyle/magesuite":"^5.0.0",
"smile/elasticsuite":"^2.8.5"

Thank you!
