### ISSUE TITLE
Category Icon display

### ISSUE THREAD

**Issue by ggm-dev** [magesuite/theme-creativeshop#64]
Hi All - I just started uploading category icons and expected them to appear in main nav automatically.  I can't for the life of me find any config settings or xml settings.  I did find a setting for mobile navigation but that's it.  Can anyone point me in the right direction?  Thanks!

➜  2html git:(m242) ✗ ack 'show_category_icon' vendor/creativestyle
vendor/creativestyle/magesuite-navigation/view/frontend/layout/navigation_mobile_index.xml
9:                <argument name="show_category_icon_subcats" xsi:type="boolean">false</argument>

**Comment by mborkowski** [comment]
Hello,
So first of all you have to enable the option via XML you posted. Secondly, every single change in navigation requires cache cleaning - we've got our own cache for nav added and it's very aggressive. Let me know if that helped

**Comment by ggm-dev** [comment]
Thanks for quick reply - for good measure I switched to theme-creativesuite and enabled in theme-creativesuite to make sure I didn't have something wacky in my child theme:
vendor/creativestyle/magesuite-navigation/view/frontend/layout/navigation_mobile_index.xml
9:                <argument name="show_category_icon_subcats" xsi:type="boolean">true</argument>

Built the theme, cleared all caches and manually restarted varnish this time and lo-and behold, the icons now show in off-canvas menu!  But they are still not showing in main desktop nav. Is there another xml config setting that I'm not seeing?

Thanks!

**Comment by mborkowski** [comment]
Yeah, also i the same dir, in `default.xml` you can enable it for desktop nav:
```
<referenceBlock name="navigation.main">
     <arguments>
         <argument name="show_category_icon_subcats" xsi:type="boolean">true</argument>
         <argument name="show_category_icon_root" xsi:type="boolean">false</argument>
     </arguments>
 </referenceBlock>
```

**Comment by ggm-dev** [comment]
Didn't occur to to just add it when I couldn't find it.  Doh!  

Thank you so much - have a great one.
