### ISSUE TITLE
Menu in mobile version not visible. ( bug in mobile version )

### ISSUE THREAD

**Issue by onsite12** [magesuite/theme-creativeshop#70]
When I click the hamburger icon on the mobile version the menu is not visible. I only see the login function + option to change currency. 

Running Magento 2.4.1
How to solve this?
![image](https://user-images.githubusercontent.com/82204564/114943098-c598f580-9e45-11eb-8564-3a9b5ecf32d7.png)

This option is on:
![image](https://user-images.githubusercontent.com/82204564/114996848-8a2b1500-9e9f-11eb-8623-c3cc32cb552d.png)

**Comment by jrswebdesign** [comment]
I have the same issue! How to fix this?

**Comment by thomas7467** [comment]
Same issue here, some items are shown, some other are hidden.

**Comment by onsite12** [comment]
> Same issue here, some items are shown, some other are hidden.

Try going to magento --> categories --> open categorie --> turn off include in mobile navigation. 
Save it, then turn it on again and save it again.

Flush cache. 
This solved it for me
