### ISSUE TITLE
Final migration from dev url to live

### ISSUE THREAD

**Issue by ggm-dev** [magesuite/theme-creativeshop#88]
Hi all - Any feedback or input would be appreciated. 

I'm getting close to going live with a magesuite based site on 2.4.2p1.  

In checking things in DB I was reminded that our dev url and admin path are both hardcoded in the JSON data in all of the content_constructor_content columns in various db tables (cms,category,product).    Obviously the url will change when we go live.   Admin path in this case will also change. 

I've had no issues moving data around from our dev site to my local, but the url in dev site has always been live. . just trying to anticipate any issues before launch.    I don't think it will be an issue - magesuite must parse through the json data to update urls as needed. . . 

BUT, just in case I do need to address the urls, is there a refresh that I'm missing that will rewrite urls in the json data or is it something that I need to do directly in the db?    Maybe someone has a script to share?:-)

Thanks everyone!

David

**Comment by diwipl** [comment]
There should be no issue unless anyone directly put domains into URL fields for example. Otherwise for all generated urls domain should be taken from current configuration.

**Comment by ggm-dev** [comment]
Thanks!
