### ISSUE TITLE
yarn build generates emtpy file in app/design thus styles are not applied

### ISSUE THREAD

**Issue by Lukas-G21** [magesuite/theme-creativeshop#90]
Magento 2.4.2
creativestyle/magesuite: 8.0.0
creativestyle/theme-creativeshop: v12.1.10

When running yarn build on child theme it generates empty file. E.g.: `app/design/frontend/creativestyle/theme-custom/web/css/image-teaser.css` is generated empty though no customizations are done to it on child theme. This might be the related to why on frontend content constructor components, product tiles grid are missing styles. 
![Screenshot from 2021-09-08 13-56-44](https://user-images.githubusercontent.com/37333986/133034461-9f52455d-d47d-4c6b-a9ef-157e5e6a323a.png)
Above image shows how styles are not applied to classes. 
Note: yarn install & yarn build passes with no errors.

**Comment by marcoveeneman** [comment]
I'm facing a similar issue as you described here, but with magento 2.4.3 / magesuite 9 / creativeshop 15 at the moment. How did you solve this?
