### ISSUE TITLE
Customers created in database by page-cache-warmer module

### ISSUE THREAD

**Issue by ggm-dev** [magesuite/theme-creativeshop#96]
Can anyone explain why this exists in the page cache warming module?

https://github.com/magesuite/page-cache-warmer/blob/1.x/Service/CustomerCreator.php

**Comment by diwipl** [comment]
It's there to warm up pages for specific customer groups since varnish cache is dependant on x-magento-vary cookie that contains customer group.

The easiest way to do it is to create fake accounts with specific customer group, log into them and warmup pages while being logged in.

**Comment by ggm-dev** [comment]
Thanks for super quick response!   I'll worry no more.   

Cheers - 
David
